services:
  - type: web
    name: musight-backend
    env: node
    buildCommand: npm install && npm run prisma:generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: musight-db
          property: connectionString
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SPOTIFY_REDIRECT_URI
        sync: false
      - key: JWT_SECRET
        sync: false

databases:
  - name: musight-db
    plan: free
    databaseName: musight
    user: musight_user

